### ISSUE TITLE
TFPayload connector

### ISSUE THREAD

**Issue by kaklik** [UniversalScientificTechnologies/SPACEDOS02#6]
Pro použití v UAV je potřeba přidat ještě [konektor pro připojení TFGPS](https://github.com/ThunderFly-aerospace/TFGPS01#payload-conector). Ideálně obdobně, jako je vyřešeno na THUNDERMILL.

**Comment by ChroustJan** [comment]
@kaklik prosím blíže specifikovat. Nechápu význam tohoto konektoru. Proč by měla jít GPS přes SPACEDOS. GPS by měla jít do TF-UNIPAYLOAD

**Comment by roman-dvorak** [comment]
Jde především o to, aby spacedos znal přesný čas a podle něj (například) předával naměřená data dále (do autopilota).


Měl by tam jít přípojit 8 pinový konektor z GPS pro payload:

![obrazek](https://user-images.githubusercontent.com/5196729/147094763-9303b797-921b-4630-bbdd-aadfeec913b6.png)

**Comment by kaklik** [comment]
> @kaklik prosím blíže specifikovat. Nechápu význam tohoto konektoru. Proč by měla jít GPS přes SPACEDOS. GPS by měla jít do TF-UNIPAYLOAD

V případě použití SPACEDOSu je přece TFUNIPAYLOAD ten stejný procesor jako je ve SPACEDOS.   Je to stejná situace jako THUNDERMILL.

Ten konektor je logické přidat na SPACEDOS i z toho důvodu, že je pravděpodobné, že SPADEDOS potažmo AIRDOS se budou v některých případech používat samostatně v kombinaci s GPS přijímačem. 

Bližší specifikaci toho konektoru dal Roman v tabulce výše. Její originální zdroj je ale [tady](https://github.com/ThunderFly-aerospace/TFGPS01#payload-conector).

**Comment by ChroustJan** [comment]
@kaklik v případě použití THUNDERMILL tam budou dvě GPS? Neměla by být jedna v TFUNIPAYLOAD a ostatní si ty data spíš brát? Nebo lépe řečeno TFUNIPAYLOAD přidávat časovou značku ke všem záznamům?

**Comment by ChroustJan** [comment]
@kaklik potřebuji definovat propojení konektoru s procesorem, aby bylo možné zvážit, jak moc velká je to komplikace:
![image](https://user-images.githubusercontent.com/9783606/147346039-3fcdff1f-ce32-4328-9d0e-fd56a5e05ac9.png)

Procesor:
![image](https://user-images.githubusercontent.com/9783606/147346091-7784064a-0e74-4927-9004-dec6e932e623.png)

**Comment by kaklik** [comment]
> @kaklik v případě použití THUNDERMILL tam budou dvě GPS? Neměla by být jedna v TFUNIPAYLOAD a ostatní si ty data spíš brát? Nebo lépe řečeno TFUNIPAYLOAD přidávat časovou značku ke všem záznamům?

Já nerozumím tomu na co se ptáš. Jde ti o situaci, kdy bude na UAV víc snímačů najednou? Například THUNDERMILL a AIRDOS zároveň? 

Přidání časové značky k záznamům má obecný problém, že časová značka musí být přidávána co nejblíže k měřeným datům, jinak se ztrácí její význam. Nerozumím proto tomu, jak by vložení další desky (TFUNIPAYLOAD) do systému zlepšilo situaci. 

Pokud ti ale jde o tu situaci více měřících zařízení využívajících TFGPS zároveň, tak zde jsme omezeni počtem UART portů, které autopilot má. V takovém případě pak až do naplnění tohoto omezeného počtu snímačů, se domnívám že, TFPayload konektor na TFGPS stačí pouze elektricky rozdělit do více vodičů. Nejspíše sletováním více vodičů k sobě. Profesionálnější řešení by asi bylo na to navrhout PCB.

**Comment by kaklik** [comment]
> @kaklik potřebuji definovat propojení konektoru s procesorem, aby bylo možné zvážit, jak moc velká je to komplikace: ![image]

Tak zapojení by se hodilo zachovat co největší míře stejné jako to je v případě [THUNDERMILL](https://github.com/mlab-modules/USTTHUNDERMILLPCB01/blob/1f451887b65ddf556598e68d01f601bc215d85c5/hw/sch_pcb/USTTHUNDERMILLPCB01A/USTTHUNDERMILLPCB01A.pdf) tj. takhle: 

![image](https://user-images.githubusercontent.com/1194177/147369047-6e7bab07-d364-4c57-8b2d-9cc29f773e7f.png)

U pinů, u kterých to není možné, tak ty je nutné přesunout na nějaké jiné volné a na PCB zapojitelné piny na MCU. Myslím že konkrétně jde akorát o piny GEO_STAT a EXTINT, které zrovna mohou být zapojeny asi na jakýkoliv pin.

**Comment by kaklik** [comment]
Tato úprava je realizována v [USTSIPIN02A](https://github.com/ust-modules/USTSIPIN02), který tím pokrývá tento use case.
